### ISSUE TITLE
Prisma issue over vercel

### ISSUE THREAD

**Issue by ganesh-swami** [ganesh-swami/shopaan#18]
PrismaClientInitializationError: Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.

Learn how: https://pris.ly/d/vercel-build
    at ga (/var/task/node_modules/.pnpm/@prisma+client@5.17.0_prisma@5.17.0/node_modules/@prisma/client/runtime/library.js:32:69)
    at new t (/var/task/node_modules/.pnpm/@prisma+client@5.17.0_prisma@5.17.0/node_modules/@prisma/client/runtime/library.js:130:739)
    at 405 (/var/task/.next/server/chunks/89.js:1:11119)
    at t (/var/task/.next/server/webpack-runtime.js:1:127)
    at 2085 (/var/task/.next/server/chunks/89.js:1:11554)
    at Function.t (/var/task/.next/server/webpack-runtime.js:1:127)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c (/var/task/.next/server/chunks/89.js:1:2260)
    at async /var/task/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
    at async rR (/var/task/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978) {
  clientVersion: '5.17.0',
  errorCode: undefined,
  digest: '976048596'
}

**Comment by ganesh-swami** [comment]
#19
